PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/b9ad92c3660dcde761592a08bdc3ae0d8d68a7c8

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/fdf1837077104e80912a2c46ff159fdacc8b06f9) in current PX4/master (2193cce50b26a68b425e56caeeaaf462f1524072)
https://github.com/PX4/NuttX/compare/fdf1837077104e80912a2c46ff159fdacc8b06f9...b9ad92c3660dcde761592a08bdc3ae0d8d68a7c8

b9ad92c366 (HEAD, origin/master) boards/arm/stm32h7/nucleo-h743zi: Add pwm example configuration
e1d35096cf arch/arm/src/imxrt/Kconfig: Fixes IMXRT_HAVE_LCD to only be selected by 1052 and 1062 and misc. typos
8469de724a Fixes build issues with IMXRT Qencoder
cfb7561e77 arch/arm/src/armv7-a/arm_vectors.S:  Fix clobbered register in SMP mode.
5f306b0461 Run all .c and .h files modified by PR 249 through nxstyle.
18ba6eb076 boards/sim: Update README.txt for network setup
5e99e64d9f sim/net: Replace the busy polling with work
5a00657ac4 arch/sim: Change CONFIG_NET_ETHERNET to CONFIG_SIM_NETDEV
6b1187b402 arch/sim: Change the return type of netdriver_setmacaddr to void
582b2af912 arch/sim: Change syslog to printf in up_tapdev.c

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/44b8c9c5aa8f2eeb1e742c6a89f9530258fa5b28

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (2193cce50b26a68b425e56caeeaaf462f1524072)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...44b8c9c5aa8f2eeb1e742c6a89f9530258fa5b28

44b8c9c5 (HEAD -> master, origin/master) apps/examples/tcpblaster:  Fix compile errors in loopback mode.
539d0854 examples: elf: Fix warnings when compiled for RISC-V 64bit
779197c6 Ensure all source code end with one and only one newline
4a13a089 testing/smp: Replace up_cpu_index with sched_getcpu
d2e1c8a4 apps/wireless/gs2200m/gs2200m_main.c:  Eliminate a warning
c8dbd59e netutils/telnetd/telnetd_daemon.c: Avoid a warning if CONFIG_NET_SOCKOPTS=n
d2522e28 apps/netutils/telnetd:  Fix undefined reference to setsockopt.
f14aead5 Shouldn't use local readline in telnet
960a92c6 (origin/master_nxp_drone_boards) Make SO_REUSEADDR not mandatory in netlib
a5dff52a Change unimplemented requests behaviour in gs2200m